title: Revati Tambe
description: Welcome to my space on the Internet.
author:
  name: Revati Tambe
  email: 24revati@gmail.com
  github: https://github.com/djarty24
copyright_year: 2023

theme: jekyll-dewey-decimal

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge